name: Metrics

on:
  # Runs once per day + manual trigger
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write   # Allow writing the generated SVG to your repo

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Built-in token works for public repos
          token: ${{ secrets.PAT_TOKEN }}

          # Profile config
          user: Bismay-exe
          template: classic
          filename: metrics.svg
          config_timezone: Asia/Kolkata

          # Sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_colors: github          

          plugin_lines: yes

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_stars: yes
          plugin_stars_limit: 3
