name: Language Pie Chart

on:
  schedule:
    - cron: "0 0 * * 0" # weekly (Sunday midnight)
  workflow_dispatch:

jobs:
  pie:
    runs-on: ubuntu-latest
    steps:
      - uses: JayKan/github-stats-pie@v1.2.0
        with:
          username: Bismay-exe
          output: pie.png

      - name: Commit Pie Chart
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update language pie chart"
          file_pattern: pie.png
